### ISSUE TITLE
Frontend: Frontend not loading

### ISSUE THREAD

**Issue by kasonde** [strapi/internal-lms#30]
I'm not sure if it's because I've never logged in before but the application currently isn't loading up. The error I'm getting is shown below: 

![image](https://github.com/user-attachments/assets/2ebf34a3-5c2b-46bc-b46b-490842750af0)

**Comment by kasonde** [comment]
The problem is here: https://github.com/strapi/internal-lms/blob/1d4446003d0e11f74dc958936256b8d8d8c01e5d/frontend/src/context/auth.tsx#L6C1-L14C5

Since you are checking to see if context is set i.e: `!context` the value returns `null` as stipulated by the default context values and throwing an error.

**Comment by derrickmehaffy** [comment]
^ Fixed in PR
